### ISSUE TITLE
Broken in Safari 8.0.7 on OSX 10.10.4

### ISSUE THREAD

**Issue by brekk** [react-designer/react-designer#4] opened 2016-02-07 17:17 UTC
_http://fatiherikli.github.io/react-designer/_ : 

```
[Error] SyntaxError: Attempted to redefine property 'fontFamily'.
    (anonymous function) (bundle.js, line 26)
```

**Comment by fatiherikli** [comment] 2016-02-08 21:28
I cannot reproduce on Safari 9.0.

Is there anyone who have an idea about how can I fix this?

**Comment by brekk** [comment] 2016-02-08 22:18
I'm not 100%, but my guess is that somewhere `fontFamily` is being defined as a `const` and then it is trying to be redefined later on.

Guessing it lives in one of these files: https://github.com/fatiherikli/react-designer/search?utf8=✓&q=fontFamily

**Comment by fatiherikli** [comment] 2016-02-08 22:37
I guess I found the problem. Could you try again? If it works, I'll release a minor version update.

**Comment by brekk** [comment] 2016-02-08 23:06
Retried; same issue, but now it's on line 27.

**Comment by fatiherikli** [comment] 2016-02-08 23:13
Weird. I'll try to downgrade my Safari to 8, and investigate.

**Comment by wassgha** [comment] 2019-05-10 14:27
Closing for now, please reopen if this is still need.

**Closed by wassgha** 2019-05-10 14:27 UTC
Labels: help wanted
